-- Generated by nwg-displays on 2026-08-09 at 18:47:25. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@165.0",
    position = "4480x-40",
    scale = 1.33,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "2560x-40",
    scale = 1.0,
    bitdepth = 10
})
