-- Generated by nwg-displays on 2026-06-09 at 15:01:56. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
    default = true
})
