-- Generated by nwg-displays on 2026-08-09 at 18:46:45. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
    default = true
})
