-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "20")

-- Settings
hl.config({
    decoration = {
        rounding = 10,
    },
    ecosystem = {
        no_donation_nag = false,
    },
    general = {
        border_size = 2,
        gaps_in = 3,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "2560x-40",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2560x1600@165.00Hz",
    position = "4480x-40",
    scale = 1.67,
    cm = "srgb",
})

-- Workspaces
hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true,
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
    default = true,
})
